/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    BabyBgSvg: typeof import('./components/BabyBgSvg.vue')['default']
    DiaryView: typeof import('./components/record/DiaryView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    GrowthMetricInput: typeof import('./components/record/GrowthMetricInput.vue')['default']
    ImagePreview: typeof import('./components/media/ImagePreview.vue')['default']
    LoadingSkeleton: typeof import('./components/common/LoadingSkeleton.vue')['default']
    MediaUploader: typeof import('./components/media/MediaUploader.vue')['default']
    MilestoneMarker: typeof import('./components/timeline/MilestoneMarker.vue')['default']
    MilestonePicker: typeof import('./components/record/MilestonePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./components/common/ThemeSwitcher.vue')['default']
    TimelineCard: typeof import('./components/timeline/TimelineCard.vue')['default']
    TimelineFilter: typeof import('./components/timeline/TimelineFilter.vue')['default']
    TimelineGroup: typeof import('./components/timeline/TimelineGroup.vue')['default']
    VideoPlayer: typeof import('./components/media/VideoPlayer.vue')['default']
    VideoThumbnailPreview: typeof import('./components/media/VideoThumbnailPreview.vue')['default']
  }
}
